apiVersion: v1
kind: Pod
metadata:
  name: api-server
  namespace: team-app
  labels:
    app: api
spec:
  containers:
  - name: api
    image: wbitt/network-multitool
    ports:
    - containerPort: 80
