apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: production
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-nginx
  name: web-nginx
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
