# webhook-deploy.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: webhook-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: ingcloudfr/image-policy-webhook:v11
          ports:
            - containerPort: 443
          volumeMounts:
            - name: webhook-certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-server-tls
