# apiVersion: v1
# kind: Pod
# metadata:
#   name: backend
#   namespace: team-green
#   labels:
#     app: backend
# spec:
#   containers:
#   - name: backend
#     image: hashicorp/http-echo
#     args:
#     - "-listen=:3000"
#     - "-text=Hello from backend"
#     ports:
#     - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: team-green
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: wbitt/network-multitool
    env:
    - name: HTTPS_PORT
      value: "3000"
    - name: HTTP_PORT
      value: "80"
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: team-green
  labels:
    app: frontend
    role: frontend
spec:
  containers:
  - name: frontend
    image: wbitt/network-multitool
---
apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: default
spec:
  containers:
  - name: tester
    image: curlimages/curl
    command: ["sh", "-c", "sleep 3600"]
