# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: web-server
#   namespace: team-silver
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: web-server
#   template:
#     metadata:
#       labels:
#         app: web-server
#     spec:
#       containers:
#       - name: server
#         image: hashicorp/http-echo
#         args:
#           - "-listen=:80"
#           - "-text=Hello from /public"
#         ports:
#         - containerPort: 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: team-silver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: docker.io/mccutchen/go-httpbin
        env:
          - name: HTTPBIN_ENV_GREETINGS
            value: "Hello from go-httpbin"
        ports:
        - containerPort: 8080