# apiVersion: v1
# kind: Service
# metadata:
#   name: web-server
#   namespace: team-silver
# spec:
#   selector:
#     app: web-server
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
  namespace: team-silver
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: httpbin