apiVersion: v1
kind: Pod
metadata:
  name: admin-tester
  namespace: team-silver
  labels:
    role: admin
spec:
  containers:
  - name: tester
    image: curlimages/curl
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: user-tester
  namespace: team-silver
spec:
  containers:
  - name: tester
    image: curlimages/curl
    command: ["sleep", "3600"]
