apiVersion: v1
kind: Pod
metadata:
  name: products-pod
  namespace: development
  labels:
    app: products
spec:
  containers:
    - name: products-pod
      securityContext:
        runAsUser: 0
      image: hashicorp/http-echo
      args:
        - "-text=Hello from products-pod on port 80"
        - "-listen=:80"
      ports:
        - containerPort: 80