apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: team-app
spec:
  selector:
    role: server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP