# apiVersion: v1
# kind: Pod
# metadata:
#   name: server
#   namespace: team-yellow
#   labels:
#     app: server
# spec:
#   containers:
#   - name: http
#     image: hashicorp/http-echo
#     args:
#     - "-text=Hello from server"
#     - "-listen=:8080"
#     ports:
#     - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: server
#   namespace: team-yellow
# spec:
#   selector:
#     app: server
#   ports:
#   - port: 8080
#     targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: server
  name: server
  namespace: team-yellow
spec:
  containers:
  - image: docker.io/mccutchen/go-httpbin
    name: server
    ports:
    - containerPort: 8080
    resources: {}
    env:
      - name: HTTPBIN_ENV_GREETINGS
        value: "Hello from go-httpbin"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: team-yellow
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: server