apiVersion: v1
kind: Pod
metadata:
  name: untrusted
  namespace: team-yellow
  labels:
    app: untrusted
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]
