apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: team-blue
  labels:
    app: backend
spec:
  containers:
    - name: web
      image: hashicorp/http-echo
      args:
        - "-text=Hello from backend on port 8080"
        - "-listen=:8080"
      ports:
        - containerPort: 8080
