apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
  namespace: team-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: team-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: docker.io/mccutchen/go-httpbin
        env:
          - name: HTTPBIN_ENV_GREETINGS
            value: "Hello from go-httpbin"
        ports:
        - containerPort: 8080
