apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: team-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: curlimages/curl
        command: ["/bin/sleep", "3600"]
