apiVersion: v1
kind: Pod
metadata:
  name: naked
  namespace: team-app
  labels:
    app: naked
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]
