apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: team-green
  labels:
    app: backend
    role: backend
spec:
  containers:
    - name: web
      image: hashicorp/http-echo
      args:
        - "-text=Hello from backend on port 8080"
        - "-listen=:8080"
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    role: backend
  name: backend-svc
  namespace: team-green
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
    role: backend
  type: ClusterIP
