apiVersion: v1
kind: Pod
metadata:
  name: api
  namespace: team-orange
  labels:
    app: api
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: team-orange
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: client-with-access
  namespace: team-blue
  labels:
    app: api
    access: cross-team
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: client-without-access
  namespace: team-blue
  labels:
    app: api
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]
---
---
apiVersion: v1
kind: Pod
metadata:
  name: client-with-access
  namespace: team-orange
  labels:
    access: cross-team
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]
---