apiVersion: v1
kind: Namespace
metadata:
  name: team-green
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: team-green
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: team-green
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
