apiVersion: v1
kind: Pod
metadata:
  name: strict-client
  namespace: staging
  labels:
    policy: strict
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
---
apiVersion: v1
kind: Pod
metadata:
  name: open-client
  namespace: staging
  labels:
    policy: open
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool

