apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: team-blue
  labels:
    app: webapp
spec:
  containers:
  - name: web
    image: python:3.9-slim
    command: ["python3", "-m", "http.server", "80"]
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 1000
